---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Asia/Shanghai}
      - WEBUI_PORT=${qbt_port:-8081}
      - DOCKER_MODS=linuxserver/mods:universal-cron #|linuxserver/mods:universal-stdout-logs|arafatamim/linuxserver-io-mod-vuetorrent
      # - LOGS_TO_STDOUT="/config/qBittorrent/logs/qbittorrent.log"
      - qbt_host=${qbt_host:-http://127.0.0.1}
      - qbt_port=${qbt_port:-8081}
      - qbt_username=${qbt_username:-admin}
      - qbt_password=${qbt_password:-adminadmin}
      - qbt_tracker_list_subscription=${qbt_tracker_list_subscription}
      - qbt_tracker_list_static=${qbt_tracker_list_static}
      - qbt_anti_leech_peer_ban_pattern=${qbt_anti_leech_peer_ban_pattern}
      - qbt_anti_leech_check_interval=${qbt_anti_leech_check_interval}
    volumes:
      - ${DIR_CONFIG:-./data/config}:/config
      - ${DIR_DOWNLOADS:-./data/downloads}:/downloads
      - ./script:/script:ro
      - ./script/config/crontabs/abc:/config/crontabs/abc
    network_mode: "host" # for listening port access from internat
    #     ports:
    #       - 8888:8888
    #       - 28888:28888
    #       - 28888:28888/udp
    restart: unless-stopped
