---
version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${QB_PUID:-1000}
      - PGID=${QB_PGID:-1000}
      - TZ=${QB_TZ:-Etc/UTC}
      - WEBUI_PORT=${QB_PORT_WEBUI:-8080}
    volumes:
      - ./data/qbittorrent/config:/config
      - qbittorrent-download:/downloads
    ports:
      - ${QB_PORT_WEBUI:-8080}:${QB_PORT_WEBUI:-8080}
      - ${QB_PORT_LISTEN:-6881}:${QB_PORT_LISTEN:-6881}
      - ${QB_PORT_LISTEN:-6881}:${QB_PORT_LISTEN:-6881}/udp
    restart: unless-stopped
volumes:
  qbittorrent-download:
    external: true